name: auto create PR for release on hotfix merge to main

on:
  pull_request:
    types:
      - closed

jobs:
  auto-create-and-pr:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' && startsWith(github.event.pull_request.head.ref, 'hotfix')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get merged commit SHA
        id: get-sha
        run: |
          set -ex
          echo "sha=$(echo ${GITHUB_SHA})" >> $GITHUB_OUTPUT
      - name: List release branches
        id: list-branches
        run: |
          set -ex
          echo "aaa: $(git branch -r)"
          BRANCHES=$(git branch -r | grep 'origin/release/' | sed 's/origin\///' | tr '\n' ',')
          echo "branches=${BRANCHES}" >> $GITHUB_OUTPUT
      - name: Set git user
        run: |
          set -ex
          git config --local user.name "${{ github.event.pusher.name }}"
          git config --local user.email "${{ github.event.pusher.email }}"
      - name: create PR for each release branch from hotfix
        run: |
          set -ex
          IFS=',' read -ra BRANCHES <<< "${{ steps.list-branches.outputs.branches }}"
          for BRANCH in "${BRANCHES[@]}"; do
            gh pr create --title "merge ${{ github.head_ref }} to ${BRANCH}" --body "This PR was automatically created by GitHub Actions." --base $BRANCH --head ${{github.head_ref}}
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
